SET TRANSACTION ISOLATION LEVEL Serializable
BEGIN TRANSACTION
SELECT * FROM Employee
ROLLBACK TRANSACTION
SET TRANSACTION ISOLATION LEVEL Serializable    --…Ë÷√ø…¥Æ––∂¡
DELETE FROM  Employee  WHERE ID = '1'

