SET TRANSACTION ISOLATION LEVEL Read Committed
BEGIN TRANSACTION
SELECT * FROM Employee
ROLLBACK TRANSACTION
SET TRANSACTION ISOLATION LEVEL Read Committed    --设置提交读隔离级别
UPDATE Employee SET Name = '高丽'

